/**
 * Auto-generated from Tirap_Performance_Index_v2 Updated.xlsx
 * Regenerate: node backend/scripts/generate-kpi-assets.js
 */
export const TOTAL_DEPT_WEIGHT = 100;
export const DEPT_KPI_GUIDES = {
  "D01": {
    "deptId": "D01",
    "deptName": "Health Service Delivery",
    "kra": "H - Health Service Delivery",
    "owner": "DMO (District Medical Officer)",
    "deptWeight": 9.68,
    "workbookWeight": 12,
    "deptContributionPct": 9.68,
    "indicatorCount": 12,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D01",
        "num": 1,
        "name": "PHC Functionality Score (% of PHCs scoring ≥70% on 6-parameter audit)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total PHCs and Scoring ≥70%. Score = (Scoring ≥70% ÷ Total PHCs) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 2,
        "name": "Institutional Delivery Rate",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Deliveries and Institutional Deliveries. Score = (Institutional Deliveries ÷ Total Deliveries) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 3,
        "name": "Full Immunisation Coverage (children 0-1 yr)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Registered Children (0–1 yr) and Fully Immunized. Score = (Fully Immunized ÷ Registered Children (0–1 yr)) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 4,
        "name": "eSanjeevani Tele-OPD Consults per active SC",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Active Sub-Centres and Tele-OPD Consults. Score = (Tele-OPD Consults ÷ Active Sub-Centres) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 5,
        "name": "ANC 4 Visits Completed (% of registered pregnancies)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Registered Pregnancies and With 4 ANC Visits. Score = (With 4 ANC Visits ÷ Registered Pregnancies) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 6,
        "name": "Ayushman Card Coverage in Priority Villages",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Households (Priority Villages) and Households with Ayushman Card. Score = (Households with Ayushman Card ÷ Total Households (Priority Villages)) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 7,
        "name": "Drug Stock-out Days at PHCs (cumulative across district)",
        "unit": "days",
        "unitLabel": "days",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total PHCs and Stock-out Days (This Month). Score = (Stock-out Days (This Month) ÷ Total PHCs) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D01",
        "num": 8,
        "name": "OST (Opioid Substitution) Active Patients",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 300,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Sanctioned OST Capacity and Active OST Patients. Score = (Active OST Patients ÷ Sanctioned OST Capacity) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 9,
        "name": "De-addiction Centre Treatment Retention (3-month)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Enrolled 3 Months Ago and Retained at 3 Months. Score = (Retained at 3 Months ÷ Enrolled 3 Months Ago) × 100. Target: 100%."
      },
      {
        "deptId": "D01",
        "num": 10,
        "name": "TB Case Notification Rate (per lakh population)",
        "unit": "count",
        "unitLabel": "rate",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 225,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter District Population and TB Cases Notified. Score = (TB Cases Notified ÷ District Population) × 100000. Target: 100."
      },
      {
        "deptId": "D01",
        "num": 11,
        "name": "Maternal Deaths (this month, district total)",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Registered Mothers and Maternal Deaths. Score = (Maternal Deaths ÷ Registered Mothers) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D01",
        "num": 12,
        "name": "Infant Deaths (this month, district total)",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Registered Infants and Infant Deaths. Score = (Infant Deaths ÷ Registered Infants) × 100. Target: 0% (lower is better)."
      }
    ]
  },
  "D02": {
    "deptId": "D02",
    "deptName": "Education Attendance & Outcomes",
    "kra": "E - Education Attendance & Outcomes",
    "owner": "DDSE (Deputy Director, School Education)",
    "deptWeight": 9.68,
    "workbookWeight": 12,
    "deptContributionPct": 9.68,
    "indicatorCount": 12,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D02",
        "num": 1,
        "name": "Teacher Attendance Rate (Govt Schools)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Teachers and Teachers Present. Score = (Teachers Present ÷ Total Teachers) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 2,
        "name": "Student Attendance Rate (Classes 1-8)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Students and Students Present. Score = (Students Present ÷ Total Students) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 3,
        "name": "FLN Reading Proficiency, Class 3 (NIPUN Bharat)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Students Assessed and Students Achieving Proficiency. Score = (Students Achieving Proficiency ÷ Students Assessed) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 4,
        "name": "Student Retention Rate",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Students at Start of Academic Year and Students Continuing in School. Score = (Students Continuing in School ÷ Students at Start of Academic Year) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 5,
        "name": "Schools with Functional Toilets (Separate Boys/Girls)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Schools and Schools with Functional Toilets. Score = (Schools with Functional Toilets ÷ Total Schools) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 6,
        "name": "Schools with Drinking Water Facility",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Schools and Schools with Drinking Water Facility. Score = (Schools with Drinking Water Facility ÷ Total Schools) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 7,
        "name": "Class 10 Board Pass Rate",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Students Appeared and Students Passed. Score = (Students Passed ÷ Students Appeared) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 8,
        "name": "Class 12 Board Pass Rate",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Students Appeared and Students Passed. Score = (Students Passed ÷ Students Appeared) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 9,
        "name": "Out-of-School Children Identified & Mainstreamed",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Children Identified (Out-of-School) and Children Mainstreamed. Score = (Children Mainstreamed ÷ Children Identified (Out-of-School)) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 10,
        "name": "Teacher Training Completion",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual Training Target (Days) and Training Days Completed. Score = (Training Days Completed ÷ Annual Training Target (Days)) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 11,
        "name": "Schools Receiving Mid-Day Meal on All Working Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Schools and Schools Receiving Mid-Day Meal Daily. Score = (Schools Receiving Mid-Day Meal Daily ÷ Total Schools) × 100. Target: 100%."
      },
      {
        "deptId": "D02",
        "num": 12,
        "name": "EMRS / Ashram School Hostel Occupancy",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Hostel Capacity and Occupied Seats. Score = (Occupied Seats ÷ Total Hostel Capacity) × 100. Target: 100%."
      }
    ]
  },
  "D03": {
    "deptId": "D03",
    "deptName": "Anganwadi & ECCE",
    "kra": "A - Anganwadi & ECCE",
    "owner": "DPO (ICDS)",
    "deptWeight": 7.26,
    "workbookWeight": 8,
    "deptContributionPct": 7.26,
    "indicatorCount": 9,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D03",
        "num": 1,
        "name": "AWC Functionality Score (% scoring ≥70% on 5-parameter audit)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total AWCs and Functional AWCs (≥70% Score). Score = (Functional AWCs (≥70% Score) ÷ Total AWCs) × 100. Target: 100%."
      },
      {
        "deptId": "D03",
        "num": 2,
        "name": "Children 0-6 Registered in ICDS MIS",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Children (0–6 Years) and Registered in ICDS MIS. Score = (Registered in ICDS MIS ÷ Target Children (0–6 Years)) × 100. Target: 100%."
      },
      {
        "deptId": "D03",
        "num": 3,
        "name": "AWCs Running Daily Pre-school Activity",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total AWCs and AWCs with Daily Pre-school Activity. Score = (AWCs with Daily Pre-school Activity ÷ Total AWCs) × 100. Target: 100%."
      },
      {
        "deptId": "D03",
        "num": 4,
        "name": "Saksham AWC Upgrade Status (Cumulative Count)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual Target AWCs and Upgraded Saksham AWCs (FY Cumulative). Score = (Upgraded Saksham AWCs (FY Cumulative) ÷ Annual Target AWCs) × 100. Target: 100%."
      },
      {
        "deptId": "D03",
        "num": 5,
        "name": "Take-Home Ration Distribution Coverage",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Eligible Beneficiaries and Beneficiaries Covered. Score = (Beneficiaries Covered ÷ Eligible Beneficiaries) × 100. Target: 100%."
      },
      {
        "deptId": "D03",
        "num": 6,
        "name": "Hot Cooked Meal Days (per AWC per month)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total AWCs and AWCs Providing Hot Cooked Meals. Score = (AWCs Providing Hot Cooked Meals ÷ Total AWCs) × 100. Target: 100%."
      },
      {
        "deptId": "D03",
        "num": 7,
        "name": "Severely Underweight Children (% of registered 0-6)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Registered Children (0–6 Years) and Severely Underweight Children. Score = (Severely Underweight Children ÷ Registered Children (0–6 Years)) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D03",
        "num": 8,
        "name": "Stunting Rate (Class 1 entrants, annual)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 0,
        "polarity": "LOWER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Children Assessed (Class 1 Entrants) and Stunted Children. Score = (Stunted Children ÷ Children Assessed (Class 1 Entrants)) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D03",
        "num": 9,
        "name": "AWWs with Smartphone & POSHAN App Active",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 11.11,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total AWWs and AWWs Active on POSHAN App. Score = (AWWs Active on POSHAN App ÷ Total AWWs) × 100. Target: 100%."
      }
    ]
  },
  "D04": {
    "deptId": "D04",
    "deptName": "Drug Demand-Reduction & Youth",
    "kra": "D - Drug Demand-Reduction & Youth",
    "owner": "DC + DMO + SP (joint)",
    "deptWeight": 6.45,
    "workbookWeight": 10,
    "deptContributionPct": 6.45,
    "indicatorCount": 8,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D04",
        "num": 1,
        "name": "New Patients Inducted into De-addiction Programme",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Sanctioned Treatment Capacity and New Patients Inducted. Score = (New Patients Inducted ÷ Sanctioned Treatment Capacity) × 100. Target: 100%."
      },
      {
        "deptId": "D04",
        "num": 2,
        "name": "Recovered Users Placed in Skilling/Employment",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Recovered Users Eligible and Placed in Skilling/Employment. Score = (Placed in Skilling/Employment ÷ Recovered Users Eligible) × 100. Target: 100%."
      },
      {
        "deptId": "D04",
        "num": 3,
        "name": "Peer Counsellors Active (recovered users)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Sanctioned Peer Counsellor Posts and Active Peer Counsellors. Score = (Active Peer Counsellors ÷ Sanctioned Peer Counsellor Posts) × 100. Target: 100%."
      },
      {
        "deptId": "D04",
        "num": 4,
        "name": "School-Based Drug Awareness Sessions Conducted",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Schools Targeted and Drug Awareness Sessions Conducted. Score = (Drug Awareness Sessions Conducted ÷ Schools Targeted) × 100. Target: 100%."
      },
      {
        "deptId": "D04",
        "num": 5,
        "name": "Sports Tournaments at Circle Level Held",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Circles in District and Sports Tournaments Held. Score = (Sports Tournaments Held ÷ Circles in District) × 100. Target: 100%."
      },
      {
        "deptId": "D04",
        "num": 6,
        "name": "Football League Registered Teams",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 120,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Teams (League) and Registered Teams. Score = (Registered Teams ÷ Target Teams (League)) × 100. Target: 100%."
      },
      {
        "deptId": "D04",
        "num": 7,
        "name": "Youth Skilling Enrolments (current month)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Monthly Skilling Target and Youth Enrolments This Month. Score = (Youth Enrolments This Month ÷ Monthly Skilling Target) × 100. Target: 100%."
      },
      {
        "deptId": "D04",
        "num": 8,
        "name": "NDPS Cases Registered + Disposal Status",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter NDPS Cases Registered and NDPS Cases Disposed. Score = (NDPS Cases Disposed ÷ NDPS Cases Registered) × 100. Target: 100%."
      }
    ]
  },
  "D05": {
    "deptId": "D05",
    "deptName": "Sanitation, Cleanliness & Urban Services",
    "kra": "S - Sanitation, Cleanliness & Urban Services",
    "owner": "TMC / Municipal Cmsr + SDO",
    "deptWeight": 4.84,
    "workbookWeight": 6,
    "deptContributionPct": 4.84,
    "indicatorCount": 6,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D05",
        "num": 1,
        "name": "ODF-Plus Villages Declared & Sustained (cumulative)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual ODF-Plus Target (Villages) and Villages Declared ODF-Plus (FY Cumulative). Score = (Villages Declared ODF-Plus (FY Cumulative) ÷ Annual ODF-Plus Target (Villages)) × 100. Target: 100%."
      },
      {
        "deptId": "D05",
        "num": 2,
        "name": "Khonsa Town Door-to-Door Waste Collection Coverage",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Households (Khonsa Town) and Households with Door-to-Door Collection. Score = (Households with Door-to-Door Collection ÷ Total Households (Khonsa Town)) × 100. Target: 100%."
      },
      {
        "deptId": "D05",
        "num": 3,
        "name": "Public Toilets Functional (% of constructed)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Public Toilets Constructed and Functional Public Toilets. Score = (Functional Public Toilets ÷ Total Public Toilets Constructed) × 100. Target: 100%."
      },
      {
        "deptId": "D05",
        "num": 4,
        "name": "Swachh Tirap Awards Participating Villages",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 150,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Participating Villages and Villages Participating in Swachh Tirap. Score = (Villages Participating in Swachh Tirap ÷ Target Participating Villages) × 100. Target: 100%."
      },
      {
        "deptId": "D05",
        "num": 5,
        "name": "Waste Segregation at Source (% HHs in town)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Households (Town) and Households Segregating Waste. Score = (Households Segregating Waste ÷ Total Households (Town)) × 100. Target: 100%."
      },
      {
        "deptId": "D05",
        "num": 6,
        "name": "Drains Cleaned Pre-Monsoon (% of urban drains)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Urban Drains and Drains Cleaned Pre-Monsoon. Score = (Drains Cleaned Pre-Monsoon ÷ Total Urban Drains) × 100. Target: 100%."
      }
    ]
  },
  "D06": {
    "deptId": "D06",
    "deptName": "Infrastructure, Roads & Connectivity",
    "kra": "I - Infrastructure, Roads & Connectivity",
    "owner": "PWD SE + PMGSY PIA",
    "deptWeight": 6.45,
    "workbookWeight": 8,
    "deptContributionPct": 6.45,
    "indicatorCount": 8,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D06",
        "num": 1,
        "name": "PWD Road Condition (% rated passable, dry season)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Road Length Assessed (km) and Road Length Passable (Dry Season). Score = (Road Length Passable (Dry Season) ÷ Total Road Length Assessed (km)) × 100. Target: 100%."
      },
      {
        "deptId": "D06",
        "num": 2,
        "name": "PWD Road Condition (% passable, monsoon)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Road Length Assessed (km) and Road Length Passable (Monsoon). Score = (Road Length Passable (Monsoon) ÷ Total Road Length Assessed (km)) × 100. Target: 100%."
      },
      {
        "deptId": "D06",
        "num": 3,
        "name": "PMGSY Projects On-Schedule (%)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total PMGSY Projects and Projects On Schedule. Score = (Projects On Schedule ÷ Total PMGSY Projects) × 100. Target: 100%."
      },
      {
        "deptId": "D06",
        "num": 4,
        "name": "JJM Tap Connections Functional",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total JJM Tap Connections and Functional Tap Connections. Score = (Functional Tap Connections ÷ Total JJM Tap Connections) × 100. Target: 100%."
      },
      {
        "deptId": "D06",
        "num": 5,
        "name": "Villages with 24x7 Power",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Villages and Villages with 24×7 Power. Score = (Villages with 24×7 Power ÷ Total Villages) × 100. Target: 100%."
      },
      {
        "deptId": "D06",
        "num": 6,
        "name": "Mobile Network Coverage (villages with 4G)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Villages and Villages with 4G Coverage. Score = (Villages with 4G Coverage ÷ Total Villages) × 100. Target: 100%."
      },
      {
        "deptId": "D06",
        "num": 7,
        "name": "Bridges/Culverts Damaged & Awaiting Repair",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Bridges and Culverts and Damaged and Awaiting Repair. Score = (Damaged and Awaiting Repair ÷ Total Bridges and Culverts) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D06",
        "num": 8,
        "name": "Power Outage Hours (district total, monthly)",
        "unit": "hours",
        "unitLabel": "hours",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 200,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Possible Supply Hours and Outage Hours This Month. Score = (Outage Hours This Month ÷ Total Possible Supply Hours) × 100. Target: 0% (lower is better)."
      }
    ]
  },
  "D07": {
    "deptId": "D07",
    "deptName": "Power Supply & Distribution",
    "kra": "W - Power Supply & Distribution",
    "owner": "Executive Engineer (Power)",
    "deptWeight": 8.06,
    "workbookWeight": 6,
    "deptContributionPct": 8.06,
    "indicatorCount": 10,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D07",
        "num": 1,
        "name": "Average Daily Power Supply Hours (district HQ + circle HQs)",
        "unit": "hours",
        "unitLabel": "hours",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Location-Days (HQs × Days in Month) and Total Supply Hours. Score = (Total Supply Hours ÷ Location-Days (HQs × Days in Month)) × 100. Target: 100%."
      },
      {
        "deptId": "D07",
        "num": 2,
        "name": "Total Unscheduled Outage Hours (district aggregate, monthly)",
        "unit": "hours",
        "unitLabel": "hours",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 160,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Possible Supply Hours and Unscheduled Outage Hours. Score = (Unscheduled Outage Hours ÷ Total Possible Supply Hours) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D07",
        "num": 3,
        "name": "Villages with Functional 11kV/LT Connectivity",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Villages and Villages with Functional 11kV/LT Connectivity. Score = (Villages with Functional 11kV/LT Connectivity ÷ Total Villages) × 100. Target: 100%."
      },
      {
        "deptId": "D07",
        "num": 4,
        "name": "Households with Metered Connection (RDSS / DDUGJY)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Households and Households with Metered Connection. Score = (Households with Metered Connection ÷ Total Households) × 100. Target: 100%."
      },
      {
        "deptId": "D07",
        "num": 5,
        "name": "New Service Connection — Mean Days Application to Energisation",
        "unit": "days",
        "unitLabel": "days",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Connections Energised This Month and Total Days (Application to Energisation). Score = (Total Days (Application to Energisation) ÷ Connections Energised This Month) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D07",
        "num": 6,
        "name": "Billing Efficiency (units billed / units input)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Units Input (Energy Supplied) and Units Billed. Score = (Units Billed ÷ Units Input (Energy Supplied)) × 100. Target: 100%."
      },
      {
        "deptId": "D07",
        "num": 7,
        "name": "Collection Efficiency (revenue collected / billed)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Revenue Billed (₹) and Revenue Collected (₹). Score = (Revenue Collected (₹) ÷ Revenue Billed (₹)) × 100. Target: 100%."
      },
      {
        "deptId": "D07",
        "num": 8,
        "name": "Distribution Transformer Failure Rate (% of installed base)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Distribution Transformers and Transformers Failed This Month. Score = (Transformers Failed This Month ÷ Total Distribution Transformers) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D07",
        "num": 9,
        "name": "Solar Rooftop / PM-Surya Ghar Installations Completed (cumulative)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 150,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual Installation Target and Installations Completed (FY Cumulative). Score = (Installations Completed (FY Cumulative) ÷ Annual Installation Target) × 100. Target: 100%."
      },
      {
        "deptId": "D07",
        "num": 10,
        "name": "Critical Substation Maintenance Compliance (% schedule met)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Scheduled Maintenance Tasks and Tasks Completed On Schedule. Score = (Tasks Completed On Schedule ÷ Scheduled Maintenance Tasks) × 100. Target: 100%."
      }
    ]
  },
  "D08": {
    "deptId": "D08",
    "deptName": "Law & Order, Public Safety",
    "kra": "L - Law & Order, Public Safety",
    "owner": "Superintendent of Police",
    "deptWeight": 6.45,
    "workbookWeight": 8,
    "deptContributionPct": 6.45,
    "indicatorCount": 8,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D08",
        "num": 1,
        "name": "FIR Registration Compliance (% of complaints leading to FIR)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Complaints Received and Complaints Converted to FIR. Score = (Complaints Converted to FIR ÷ Total Complaints Received) × 100. Target: 100%."
      },
      {
        "deptId": "D08",
        "num": 2,
        "name": "Case Disposal Rate (% of pending docket disposed)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Pending Cases (Start of Month) and Cases Disposed This Month. Score = (Cases Disposed This Month ÷ Pending Cases (Start of Month)) × 100. Target: 100%."
      },
      {
        "deptId": "D08",
        "num": 3,
        "name": "NDPS Seizure-to-Treatment Referral Ratio (lower = better balance)",
        "unit": "count",
        "unitLabel": "ratio",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter NDPS Seizures and Treatment Referrals from Seizures. Score = (Treatment Referrals from Seizures ÷ NDPS Seizures) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D08",
        "num": 4,
        "name": "Crimes Against Women (FIRs registered)",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter District Population (lakhs) and CAW FIRs Registered. Score = (CAW FIRs Registered ÷ District Population (lakhs)) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D08",
        "num": 5,
        "name": "CAW Conviction Rate (% of cases reaching judgment)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter CAW Cases Reaching Judgment and Cases with Conviction. Score = (Cases with Conviction ÷ CAW Cases Reaching Judgment) × 100. Target: 100%."
      },
      {
        "deptId": "D08",
        "num": 6,
        "name": "Police Public Grievance Days Held (per month, district-wide)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Grievance Days (District) and Grievance Days Held. Score = (Grievance Days Held ÷ Target Grievance Days (District)) × 100. Target: 100%."
      },
      {
        "deptId": "D08",
        "num": 7,
        "name": "Excise / Opium Field Destruction (acres)",
        "unit": "count",
        "unitLabel": "acres",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Acres for Destruction and Acres Destroyed. Score = (Acres Destroyed ÷ Target Acres for Destruction) × 100. Target: 100%."
      },
      {
        "deptId": "D08",
        "num": 8,
        "name": "Communal/Tribal Tension Incidents",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Villages/Areas Monitored and Communal/Tribal Tension Incidents. Score = (Communal/Tribal Tension Incidents ÷ Villages/Areas Monitored) × 100. Target: 0% (lower is better)."
      }
    ]
  },
  "D09": {
    "deptId": "D09",
    "deptName": "Agriculture, Horticulture & Allied",
    "kra": "G - Agriculture, Horticulture & Allied",
    "owner": "DAO + DHO + DPM-NRLM",
    "deptWeight": 8.06,
    "workbookWeight": 8,
    "deptContributionPct": 8.06,
    "indicatorCount": 10,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D09",
        "num": 1,
        "name": "Farmer Field Demonstration Plots Active",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 300,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Demonstration Plots and Active Demonstration Plots. Score = (Active Demonstration Plots ÷ Target Demonstration Plots) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 2,
        "name": "FPOs Active with >100 Members",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target FPOs and FPOs Active with >100 Members. Score = (FPOs Active with >100 Members ÷ Target FPOs) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 3,
        "name": "KCC (Kisan Credit Card) Coverage of Farmers",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Farmer Households and Farmers with KCC. Score = (Farmers with KCC ÷ Total Farmer Households) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 4,
        "name": "PM-Kisan Beneficiaries Receiving Instalment",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total PM-Kisan Beneficiaries and Beneficiaries Who Received Instalment. Score = (Beneficiaries Who Received Instalment ÷ Total PM-Kisan Beneficiaries) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 5,
        "name": "Soil Health Cards Distributed (cumulative)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 7500,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual Soil Health Card Target and Cards Distributed (FY Cumulative). Score = (Cards Distributed (FY Cumulative) ÷ Annual Soil Health Card Target) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 6,
        "name": "Agarwood Saplings Distributed (cumulative)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 75000,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual Sapling Target and Agarwood Saplings Distributed (FY Cumulative). Score = (Agarwood Saplings Distributed (FY Cumulative) ÷ Annual Sapling Target) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 7,
        "name": "Large Cardamom Acreage Brought Under Cultivation",
        "unit": "count",
        "unitLabel": "acres",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 750,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Cardamom Acres and Acres Brought Under Cultivation. Score = (Acres Brought Under Cultivation ÷ Target Cardamom Acres) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 8,
        "name": "Mithun Vaccination Coverage",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Mithun Population and Mithun Vaccinated. Score = (Mithun Vaccinated ÷ Total Mithun Population) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 9,
        "name": "SHGs with Active Bank Credit Line",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 750,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total SHGs and SHGs with Active Bank Credit Line. Score = (SHGs with Active Bank Credit Line ÷ Total SHGs) × 100. Target: 100%."
      },
      {
        "deptId": "D09",
        "num": 10,
        "name": "DDU-GKY Skilling Placements (cumulative)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 450,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual Placement Target and DDU-GKY Placements (FY Cumulative). Score = (DDU-GKY Placements (FY Cumulative) ÷ Annual Placement Target) × 100. Target: 100%."
      }
    ]
  },
  "D10": {
    "deptId": "D10",
    "deptName": "Convergence & Saturation Villages",
    "kra": "C - Convergence & Saturation Villages",
    "owner": "DC (chair) + multi-departmental",
    "deptWeight": 6.45,
    "workbookWeight": 6,
    "deptContributionPct": 6.45,
    "indicatorCount": 8,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D10",
        "num": 1,
        "name": "Saturation Villages Where Camp Held (cumulative)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Annual Saturation Village Target and Villages Where Camp Held (FY Cumulative). Score = (Villages Where Camp Held (FY Cumulative) ÷ Annual Saturation Village Target) × 100. Target: 100%."
      },
      {
        "deptId": "D10",
        "num": 2,
        "name": "Aadhaar Saturation in Priority Villages",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Residents in Priority Villages and Residents with Aadhaar. Score = (Residents with Aadhaar ÷ Residents in Priority Villages) × 100. Target: 100%."
      },
      {
        "deptId": "D10",
        "num": 3,
        "name": "Jan Dhan Account Coverage (adult HHs)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Adult Households and Households with Jan Dhan Account. Score = (Households with Jan Dhan Account ÷ Total Adult Households) × 100. Target: 100%."
      },
      {
        "deptId": "D10",
        "num": 4,
        "name": "Ration Card Backlog (pending applications)",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Ration Card Applications Received and Pending Backlog. Score = (Pending Backlog ÷ Ration Card Applications Received) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D10",
        "num": 5,
        "name": "PMAY-G Houses Sanctioned vs Completed",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter PMAY-G Houses Sanctioned and PMAY-G Houses Completed. Score = (PMAY-G Houses Completed ÷ PMAY-G Houses Sanctioned) × 100. Target: 100%."
      },
      {
        "deptId": "D10",
        "num": 6,
        "name": "NSAP Pension Disbursement (% of beneficiaries received)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total NSAP Beneficiaries and Beneficiaries Who Received Pension. Score = (Beneficiaries Who Received Pension ÷ Total NSAP Beneficiaries) × 100. Target: 100%."
      },
      {
        "deptId": "D10",
        "num": 7,
        "name": "PM-JANMAN Plan Implementation (% of approved activities executed)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Approved PM-JANMAN Activities and Activities Executed. Score = (Activities Executed ÷ Approved PM-JANMAN Activities) × 100. Target: 100%."
      },
      {
        "deptId": "D10",
        "num": 8,
        "name": "DAJGUA District Plan Activities On-Schedule",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 12.5,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total DAJGUA Plan Activities and Activities On Schedule. Score = (Activities On Schedule ÷ Total DAJGUA Plan Activities) × 100. Target: 100%."
      }
    ]
  },
  "D11": {
    "deptId": "D11",
    "deptName": "Revenue & Land",
    "kra": "R - Revenue & Land",
    "owner": "Revenue Officer + COs",
    "deptWeight": 4.03,
    "workbookWeight": 6,
    "deptContributionPct": 4.03,
    "indicatorCount": 5,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D11",
        "num": 1,
        "name": "Land Mutation Cases Disposed Within 30 Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 20,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Mutation Cases Received and Cases Disposed Within 30 Days. Score = (Cases Disposed Within 30 Days ÷ Mutation Cases Received) × 100. Target: 100%."
      },
      {
        "deptId": "D11",
        "num": 2,
        "name": "Land Records Digitisation Coverage",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 20,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Revenue Villages/Parcels and Records Digitised. Score = (Records Digitised ÷ Total Revenue Villages/Parcels) × 100. Target: 100%."
      },
      {
        "deptId": "D11",
        "num": 3,
        "name": "Pending Court Cases Involving District (%)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 0,
        "polarity": "LOWER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 20,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Court Cases (District) and Pending Cases. Score = (Pending Cases ÷ Total Court Cases (District)) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D11",
        "num": 4,
        "name": "Public Hearing Days (CO + SDO Darbar) Held",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 20,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Public Hearing Days and Hearing Days Held (CO + SDO Darbar). Score = (Hearing Days Held (CO + SDO Darbar) ÷ Target Public Hearing Days) × 100. Target: 100%."
      },
      {
        "deptId": "D11",
        "num": 5,
        "name": "Revenue Court Cases Disposed",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 20,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Revenue Court Cases and Cases Disposed. Score = (Cases Disposed ÷ Total Revenue Court Cases) × 100. Target: 100%."
      }
    ]
  },
  "D12": {
    "deptId": "D12",
    "deptName": "Jan Suvidha (Certificates & Services)",
    "kra": "J - Jan Suvidha (Certificates & Services)",
    "owner": "OIC, Jan Suvidha (DC Office)",
    "deptWeight": 9.68,
    "workbookWeight": 6,
    "deptContributionPct": 9.68,
    "indicatorCount": 12,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D12",
        "num": 1,
        "name": "ST (Scheduled Tribe) Certificate Issued Within 15 Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter ST Certificate Applications Received and Issued Within 15 Days. Score = (Issued Within 15 Days ÷ ST Certificate Applications Received) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 2,
        "name": "PRC (Permanent Residence Certificate) Issued Within 15 Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter PRC Applications Received and Issued Within 15 Days. Score = (Issued Within 15 Days ÷ PRC Applications Received) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 3,
        "name": "TRC (Temporary Residence Certificate) Issued Within 15 Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter TRC Applications Received and Issued Within 15 Days. Score = (Issued Within 15 Days ÷ TRC Applications Received) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 4,
        "name": "Government ID Card Issued Within 15 Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Government ID Applications Received and Issued Within 15 Days. Score = (Issued Within 15 Days ÷ Government ID Applications Received) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 5,
        "name": "ILP (Inner Line Permit) Issued Within 7 Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter ILP Applications Received and Issued Within 7 Days. Score = (Issued Within 7 Days ÷ ILP Applications Received) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 6,
        "name": "Driving Licence — Applications Forwarded to DTO Within 3 Working Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Driving Licence Applications Received and Forwarded to DTO Within 3 Days. Score = (Forwarded to DTO Within 3 Days ÷ Driving Licence Applications Received) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 7,
        "name": "Driving Licence — Applications Received (volume, this month)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 120,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Expected Monthly Volume and Driving Licence Applications Received. Score = (Driving Licence Applications Received ÷ Expected Monthly Volume) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 8,
        "name": "Driving Licence — Applications Pending Forwarding (>3 days)",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Driving Licence Applications Received and Pending Forwarding >3 Days. Score = (Pending Forwarding >3 Days ÷ Driving Licence Applications Received) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D12",
        "num": 9,
        "name": "Vehicle Registration — Applications Forwarded to DTO Within 3 Working Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Vehicle Registration Applications Received and Forwarded to DTO Within 3 Days. Score = (Forwarded to DTO Within 3 Days ÷ Vehicle Registration Applications Received) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 10,
        "name": "Vehicle Registration — Applications Received (volume, this month)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Expected Monthly Volume and Vehicle Registration Applications Received. Score = (Vehicle Registration Applications Received ÷ Expected Monthly Volume) × 100. Target: 100%."
      },
      {
        "deptId": "D12",
        "num": 11,
        "name": "Vehicle Registration — Applications Pending Forwarding (>3 days)",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Vehicle Registration Applications Received and Pending Forwarding >3 Days. Score = (Pending Forwarding >3 Days ÷ Vehicle Registration Applications Received) × 100. Target: 0% (lower is better)."
      },
      {
        "deptId": "D12",
        "num": 12,
        "name": "Citizen Satisfaction with Jan Suvidha (random phone sample)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 8.33,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Citizens Surveyed and Citizens Satisfied. Score = (Citizens Satisfied ÷ Citizens Surveyed) × 100. Target: 100%."
      }
    ]
  },
  "D13": {
    "deptId": "D13",
    "deptName": "Disaster Management & Resilience",
    "kra": "M - Disaster Management & Resilience",
    "owner": "District Disaster Mgmt Officer (DDMO)",
    "deptWeight": 4.84,
    "workbookWeight": 4,
    "deptContributionPct": 4.84,
    "indicatorCount": 6,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D13",
        "num": 1,
        "name": "Disaster Preparedness Drills Conducted",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Drills Planned and Drills Conducted. Score = (Drills Conducted ÷ Drills Planned) × 100. Target: 100%."
      },
      {
        "deptId": "D13",
        "num": 2,
        "name": "Pre-Monsoon Stocking at PHCs/Schools (% complete by April)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total PHCs and Schools and Pre-Monsoon Stocking Complete by April. Score = (Pre-Monsoon Stocking Complete by April ÷ Total PHCs and Schools) × 100. Target: 100%."
      },
      {
        "deptId": "D13",
        "num": 3,
        "name": "Villages with Documented DRR Plans",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Target Villages and Villages with Documented DRR Plans. Score = (Villages with Documented DRR Plans ÷ Target Villages) × 100. Target: 100%."
      },
      {
        "deptId": "D13",
        "num": 4,
        "name": "Relief Reached Within 7 Days of Reported Incident",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Reported Incidents and Incidents with Relief Within 7 Days. Score = (Incidents with Relief Within 7 Days ÷ Reported Incidents) × 100. Target: 100%."
      },
      {
        "deptId": "D13",
        "num": 5,
        "name": "Early Warning System Coverage (flood/landslide-prone villages)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Flood/Landslide-Prone Villages and Villages with Early Warning Coverage. Score = (Villages with Early Warning Coverage ÷ Flood/Landslide-Prone Villages) × 100. Target: 100%."
      },
      {
        "deptId": "D13",
        "num": 6,
        "name": "VHF/HF Radio Backup Functional at Critical Locations",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 16.67,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Critical Locations and Locations with Functional VHF/HF Radio. Score = (Locations with Functional VHF/HF Radio ÷ Critical Locations) × 100. Target: 100%."
      }
    ]
  },
  "D14": {
    "deptId": "D14",
    "deptName": "Process, People & Citizen Grievance",
    "kra": "P - Process, People & Citizen Grievance",
    "owner": "DC Office",
    "deptWeight": 8.06,
    "workbookWeight": 6,
    "deptContributionPct": 8.06,
    "indicatorCount": 10,
    "howToEnter": [
      "Open **Data Submission** tab — only the **previous calendar month** can be entered.",
      "For each indicator, type the **actual value** in the unit shown (% / count / days / hours).",
      "Click **Submit Monthly Data** before the deadline (default: 11 PM on the 1st of the month).",
      "You may update values until the deadline passes."
    ],
    "howToCheckTargets": [
      "Open **Action Tracker** tab to see DC targets when any indicator is RED (<70 score).",
      "Expand a row to read the **target score**, **due date**, and **action plan**.",
      "Quarterly indicators: DC may set a **count target for the quarter** — your monthly entries are summed."
    ],
    "kpis": [
      {
        "deptId": "D14",
        "num": 1,
        "name": "DC Field Days Completed",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Field Days Target (DC) and Field Days Completed. Score = (Field Days Completed ÷ Field Days Target (DC)) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 2,
        "name": "SDO Field Days (avg per SDO)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Number of SDOs and Total SDO Field Days. Score = (Total SDO Field Days ÷ Number of SDOs) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 3,
        "name": "Officer Tour Diaries Submitted On-Time",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Officers Required to Submit Diaries and Tour Diaries Submitted On Time. Score = (Tour Diaries Submitted On Time ÷ Officers Required to Submit Diaries) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 4,
        "name": "GB 360 Feedback Forms Received (quarterly)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 150,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Quarterly Feedback Target and GB 360 Feedback Forms Received. Score = (GB 360 Feedback Forms Received ÷ Quarterly Feedback Target) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 5,
        "name": "Grievances Registered (PGRS-DARPAN + WhatsApp)",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 150,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Monthly Grievance Target and Grievances Registered. Score = (Grievances Registered ÷ Monthly Grievance Target) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 6,
        "name": "Grievances Disposed Within 30 Days",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Total Grievances Open and Grievances Disposed Within 30 Days. Score = (Grievances Disposed Within 30 Days ÷ Total Grievances Open) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 7,
        "name": "Citizen Satisfaction (random phone sample of closed cases)",
        "unit": "pct",
        "unitLabel": "%",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "Q",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Quarterly (cumulative count in the quarter)",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Citizens Surveyed (Closed Cases) and Citizens Satisfied. Score = (Citizens Satisfied ÷ Citizens Surveyed (Closed Cases)) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 8,
        "name": "Public Dashboard Released On Time (5th of month)",
        "unit": "count",
        "unitLabel": "yes/no",
        "target": 1,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "1 = Yes (released on 5th), 0 = No. Target: Yes."
      },
      {
        "deptId": "D14",
        "num": 9,
        "name": "Press Notes / Public Communications Issued",
        "unit": "count",
        "unitLabel": "count",
        "target": 100,
        "polarity": "HIGHER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Higher is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Monthly Communications Target and Press Notes Issued. Score = (Press Notes Issued ÷ Monthly Communications Target) × 100. Target: 100%."
      },
      {
        "deptId": "D14",
        "num": 10,
        "name": "Vacancies in Critical Posts (district total)",
        "unit": "count",
        "unitLabel": "count",
        "target": 0,
        "polarity": "LOWER",
        "freq": "M",
        "minValue": 0,
        "maxValue": 100,
        "polarityLabel": "Lower is better",
        "freqLabel": "Monthly",
        "shareInDeptPct": 10,
        "shareInTpiPct": 0.80645,
        "enterHint": "Enter Sanctioned Critical Posts and Vacant Critical Posts. Score = (Vacant Critical Posts ÷ Sanctioned Critical Posts) × 100. Target: 0% (lower is better)."
      }
    ]
  }
};

export function guideForDept(deptId) {
  return DEPT_KPI_GUIDES[deptId] || null;
}
